# Generated by Django 4.2.23 on 2025-08-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysisresult_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultreview',
            name='result_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.resultitem'),
        ),
        migrations.AlterUniqueTogether(
            name='resultreview',
            unique_together={('result_item', 'review_id')},
        ),
        migrations.RemoveField(
            model_name='resultreview',
            name='result',
        ),
    ]
