# Generated by Django 4.2.23 on 2025-08-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_resultreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultreview',
            unique_together={('result_item', 'review_id', 'review_type')},
        ),
    ]
