# Generated by Django 4.2.23 on 2025-08-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_resultreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultitem',
            name='starred',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
