# Generated by Django 4.2.23 on 2025-08-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_analysisresult_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('category', models.CharField(choices=[('hook', 'Hook'), ('promotion', 'Promotion'), ('product_option', 'Product Option'), ('review', 'Review'), ('qna', 'QnA'), ('shipping', 'Shipping'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('category',)},
            },
        ),
    ]
