# Generated by Django 4.2.23 on 2025-08-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='category',
            field=models.CharField(choices=[('hook', 'Hook'), ('promotion', 'Promotion'), ('product_option', 'Product Option'), ('review', 'Review'), ('qna', 'QnA'), ('shipping', 'Shipping'), ('selling_point', 'Selling Point'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='category',
            field=models.CharField(choices=[('hook', 'Hook'), ('promotion', 'Promotion'), ('product_option', 'Product Option'), ('review', 'Review'), ('qna', 'QnA'), ('shipping', 'Shipping'), ('selling_point', 'Selling Point'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resultdetailimage',
            name='category',
            field=models.CharField(blank=True, choices=[('hook', 'Hook'), ('promotion', 'Promotion'), ('product_option', 'Product Option'), ('review', 'Review'), ('qna', 'QnA'), ('shipping', 'Shipping'), ('selling_point', 'Selling Point'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
